name: Build&Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v**"

jobs:
  build-lin-win:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install build-essential gcc-multilib g++-multilib mingw-w64 libgl1-mesa-dev libglu1-mesa-dev libx11-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qt5-qmake libasound2-dev libportaudio2 libpulse-dev ffmpeg libxcursor-dev
      - name: Restore libacfutils dep cache
        id: restore_libacfutils_dep_cache
        uses: actions/cache/restore@v4
        with:
          path: |
            src/libacfutils/zlib
            src/libacfutils/libiconv
            src/libacfutils/libclipboard
            src/libacfutils/libpng
            src/libacfutils/libjpeg
            src/libacfutils/libxml2
            src/libacfutils/freetype
            src/libacfutils/cairo
            src/libacfutils/opus
            src/libacfutils/ssl
            src/libacfutils/curl
            src/libacfutils/shapelib
            src/libacfutils/ocr
            src/libacfutils/pcre2
            src/libacfutils/glew
            src/libacfutils/openal_soft
            src/libacfutils/cglm
            src/libacfutils/geographiclib
            src/libacfutils/lzma
          key: ${{ runner.os }}-${{ hashFiles('src/libacfutils/build_*','src/libacfutils/**/build_*','src/libacfutils/**/*.tar.*','src/libacfutils/**/*.patch', 'src/libacfutils/lzma/C/7zVersion.h' ) }}
      - name: Build libacfutils dep
        run: 'cd src/libacfutils && chmod +x build_deps &&./build_deps'
      - name: Build libacfutils redist
        run: 'cd src/libacfutils && chmod +x build_redist && ./build_redist'
      - name: Build
        run: 'chmod +x build_release && ./build_release'
      - name: Archive files
        run: zip -r BetterPushBack_lin_win.zip BetterPushback
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BetterPushBack_lin_win.zip
          path: BetterPushBack_lin_win.zip
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: BetterPushBack_lin_win.zip
          draft: true
          prerelease: true
      - name: Save libacfutils dep cache
        id: save_libacfutils_dep_cache
        uses: actions/cache/save@v4
        with:
          path: |
            src/libacfutils/zlib
            src/libacfutils/libiconv
            src/libacfutils/libclipboard
            src/libacfutils/libpng
            src/libacfutils/libjpeg
            src/libacfutils/libxml2
            src/libacfutils/freetype
            src/libacfutils/cairo
            src/libacfutils/opus
            src/libacfutils/ssl
            src/libacfutils/curl
            src/libacfutils/shapelib
            src/libacfutils/ocr
            src/libacfutils/pcre2
            src/libacfutils/glew
            src/libacfutils/openal_soft
            src/libacfutils/cglm
            src/libacfutils/geographiclib
            src/libacfutils/lzma
          key: ${{ steps.restore_libacfutils_dep_cache.outputs.cache-primary-key }}
